import tkinter as tk
import random
import base64
import os
import tkinter.font as tkFont

colorSwitch = False
menuSwitch = True
lowLim = 1
hiLim = 100
colours = ['#FF3333','#FFAC33','#FFFF33','#33FF39','#33FF39','#FFFF33','#FFAC33','#FF3333']
logo = """
AAABAAEAIyMAAAEAIABkFAAAFgAAACgAAAAjAAAARgAAAAEAIAAAAAAAJBMAAMMOAADDDgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADqQ2/8AAAD/AAAA/wAAAP/bkDr/
tv///wAAZv8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP8AAAD/AAAA/wAAAP//tmb/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAOpDb/wAAAP8AAAD/AAAA/9uQOv+2////AABm/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA//+2Zv8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6kNv/AAAA/wAAAP8AAAD/25A6/7b///8A
AGb/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD//7Zm/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ADqQ2/8AAAD/AAAA/wAAAP/bkDr/tv///wAAZv8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP//tmb/AAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOpDb/wAAAP8AAAD/AAAA/9uQOv8AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOpD/AAAA/wAAAP8AAAD/AAAA/9uQOv86kNv/
AAAA/wAAAP8AAAD/25A6/wAAAAAAAAAAAABm/wAAAP8AAAD/AAAA/wAAAP8AAAD/ZgAA/wAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6
kP8AAAD/AAAA/wAAAP8AAAD/25A6/zqQ2/8AAAD/AAAA/wAAAP/bkDr/AAAAAAAAAAAAAAD/AAAA
/wAAAP8AAAD/AAAA/wAAAP/bkDr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADqQ/wAAAP8AAAD/AAAA/wAAAP/bkDr/OpDb/wAAAP8A
AAD/AAAA/9uQOv8AAAAA2////wAAAP8AAAD/AAAA/wAAAP8AAAD/ZgAA////tv8AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOpD/AAAA
/wAAAP8AAAD/AAAA/9uQOv86kNv/AAAA/wAAAP8AAAD/25A6/wAAAABmtv//AAAA/wAAAP8AAAD/
AAAA/wAAAP//tmb//////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA6kP8AAAD/AAAA/wAAAP8AAAD/25A6/zqQ2/8AAAD/AAAA/wAA
AP/bkDr/2////wA6kP8AAAD/AAAA/wAAAP8AAAD/kDoA////2/8AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADqQ/wAAAP8AAAD/
AAAA/wAAAP/bkDr/OpDb/wAAAP8AAAD/AAAA/9uQOv9mtv//AAAA/wAAAP8AAAD/AAAA/wAAAP//
tmb/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAOpD/AAAA/wAAAP8AAAD/AAAA/9uQOv86kNv/AAAA/wAAAP8AAAD/25A6
/2a2//8AAAD/AAAA/wAAAP8AAAD/AAAA//+2Zv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6kP8AAAD/AAAA/wAAAP8A
AAD/25A6/zqQ2/8AAAD/AAAA/wAAAP/bkDr/ADqQ/wAAAP8AAAD/kDoA/5A6AP+QOgD////b/wAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAADqQ/wAAAP8AAAD/AAAA/wAAAP/bkDr/OpDb/wAAAP8AAAD/AAAA/9uQOv8AAAD/
AAAA/zoAAP//25D//9uQ///bkP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOpD/AAAA/wAAAP8AAAD/AAAA/wAA
AP86kNv/AAAA/wAAAP8AAAD/25A6/wAAAP8AAAD/25A6/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA6kP8AAAD/AAAA/wAAAP8AAAD/AAAA/zqQ2/8AAAD/AAAA/wAAAP/bkDr/AAAA/wAAAP//
/9v/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADqQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/OpDb
/wAAAP8AAAD/AAAA/9uQOv8AAAD/AAAA////2/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
OpD/AAAA/wAAAP8AAAD/AAAA/wAAAP86kNv/AAAA/wAAAP8AAAD/25A6/wAAAP8AAAD/OjoA/9u2
kP/btpD/27aQ/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6kP8AAAD/AAAA/wAAAP8AAAD/AAAA/zqQ2/8AAAD/
AAAA/wAAAP/bkDr/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD//7Zm/wAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADqQ/wAA
AP8AAAD/AAAA/wAAAP/bkDr/OpDb/wAAAP8AAAD/AAAA/9uQOv9mttv/AAA6/w0NDf8AAAD/AAAA
/wAAAP9mAAD///+2/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAOpD/AAAA/wAAAP8AAAD/AAAA/9uQOv86kNv/AAAA/wAAAP8A
AAD/25A6/wAAAACw4vr/YF1c/zs7Ov8AAAD/AAAA/wAAAP//tmb/AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6kP8AAAD/AAAA
/wAAAP8AAAD/25A6/zqQ2/8AAAD/AAAA/wAAAP/bkDr/AAAAALPd8f87LS3/WFhX/wAAAP8AAAD/
AAAA//+2Zv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAADqQ/wAAAP8AAAD/AAAA/wAAAP/bkDr/OpDb/wAAAP8AAAD/AAAA/9uQ
Ov8AAAAA4fz7/1hYV/8pKSn/AAAA/wAAAP8AAAD/25A6/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOpD/AAAA/wAAAP8AAAD/
AAAA/9uQOv86kNv/AAAA/wAAAP8AAAD/25A6/wAAAADb////AAAA/wAAAP8AAAD/AAAA/wAAAP+2
ZgD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA6kP8AAAD/AAAA/wAAAP8AAAD/25A6/zqQ2/8AAAD/AAAA/wAAAP/bkDr/AAAA
ALb///8AAAD/AAAA/wAAAP8AAAD/AAAA/9uQOv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADqQ/wAAAP8AAAD/AAAA/wAAAP/b
kDr/OpDb/wAAAP8AAAD/AAAA/9uQOv+229v/ADpm/wAAAP8AAAD/AAAA/wAAAP8AAAD//7Zm/wAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAOpD/AAAA/wAAAP8AAAD/AAAA/wAAAP86kNv/AAAA/wAAAP8AAAD/25A6/wAAAP8AAAD/
AAAA/wAAAP8AAAD/AAAA/2YAAP///7b/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6kP8AAAD/AAAA/wAAAP8AAAD/AAAA/zqQ
2/8AAAD/AAAA/wAAAP/bkDr/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/25A6/wAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ADqQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/OpDb/wAAAP8AAAD/AAAA/9uQOv8AAAD/AAAA/wAAAP8A
AAD/AAAA/wAAAP/bkDr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOpD/AAAA/wAAAP8AAAD/AAAA/wAAAP86kNv/AAAA
/wAAAP8AAAD/25A6/wAAAP8AAAD/AAAA/9uQOv/bkDr/25A6/wAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6kP8A
AAD/AAAA/wAAAP8AAAD/AAAA/zqQ2/8AAAD/AAAA/wAAAP/bkDr/AAAA/wAAAP8AAAD/25A6/9uQ
Ov/bkDr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAADqQ/wAAAP8AAAD/AAAA/wAAAP8AAAD/OpDb/wAAAP8AAAD/
AAAA/9uQOv86AAD/Zjo6///b2/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA6kNv/AAAA/wAAAP8AAAD/25A6/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADqQ2/8AAAD/AAAA/wAAAP/b
kDr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAOpDb/wAAAP8AAAD/AAAA/9uQOv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAA/wAAACAAAAD/AAAAIAAAAP8AAAAgAAAA/wAAACAAAAD/B///4AAAAMAGA//gAAAAwAYD/+AA
AADABAP/4AAAAMAEA//gAAAAwAAH/+AAAADAAA//4AAAAMAAD//gAAAAwAAP/+AAAADAAB//4AAA
AMAA///gAAAAwAD//+AAAADAAP//4AAAAMAAH//gAAAAwAAP/+AAAADAAAf/4AAAAMAEB//gAAAA
wAQH/+AAAADABAf/4AAAAMAEB//gAAAAwAQH/+AAAADAAAf/4AAAAMAAB//gAAAAwAAP/+AAAADA
AA//4AAAAMAAH//gAAAAwAAf/+AAAADAAP//4AAAAP8H///gAAAA/wf//+AAAAD/B///4AAAAA==
"""

def gen_rand(event):  
    global colorSwitch, lowLim, hiLim, colours  
    rng = random.SystemRandom()
    randvar = rng.randint(lowLim, hiLim)
    tout.set(randvar)    
    val = randvar + 100*int(colorSwitch)
    idx = (val - lowLim) // 25
    label.config(fg=colours[idx])
                             
def clear_rand(event):
	tout.set("")

def cSwitch():
    global colorSwitch
    colorSwitch = not(colorSwitch)
    
def rng99():
    global lowLim, hiLim
    lowLim = 0
    hiLim = 99
    
def rng100():
    global lowLim, hiLim
    lowLim = 1
    hiLim = 100  
    
def mSwitch(event):
    global menuSwitch
    if menuSwitch:        
        root.config(menu=emptyMenu)
        menuSwitch = not menuSwitch
        winx = root.winfo_rootx() - 1
        winy = root.winfo_rooty() + 19
        winw = root.winfo_width()
        winh = root.winfo_height() - 38
        root.geometry(f'{winw}x{winh}')
        root.geometry(f'+{winx}+{winy}')
        root.overrideredirect(1)
    else:
        root.config(menu=menubar)
        menuSwitch = not menuSwitch
        winx = root.winfo_rootx() - 7
        winy = root.winfo_rooty() - 50
        winw = root.winfo_width()
        winh = root.winfo_height() - 2
        root.geometry(f'{winw}x{winh}')
        root.geometry(f'+{winx}+{winy}')
        root.overrideredirect(0)

def decreaseFontSize():
    fontsize = fontStyle['size']
    label['text'] = fontsize - 15
    fontStyle.config(size = fontsize - 15)
    
def increaseFontSize():
    fontsize = fontStyle['size']
    label['text'] = fontsize + 15
    fontStyle.config(size = fontsize + 15)
        
icondata = base64.b64decode(logo)
tempFile = "icon.ico"
iconfile = open(tempFile,"wb")
iconfile.write(icondata)
iconfile.close()

root = tk.Tk()
root.title('RNGClick')
root.iconbitmap('icon.ico')

emptyMenu = tk.Menu(root)
menubar = tk.Menu(root)
filemenu = tk.Menu(menubar, tearoff=0)
filemenu.add_command(label="Switch Colour Order", command=cSwitch)
filemenu.add_separator()
filemenu.add_radiobutton(label="RNG from 0-99", command=rng99)
filemenu.add_radiobutton(label="RNG from 1-100", command=rng100)
filemenu.add_separator()
filemenu.add_command(label="Increase Font Size", command=increaseFontSize)
filemenu.add_command(label="Decrease Font Size", command=decreaseFontSize)
menubar.add_cascade(label="Options", menu=filemenu)
root.config(menu=menubar)

root.configure(background='black')
root.bind('<Button-1>', gen_rand)
root.bind('<Button-3>', clear_rand)
root.bind('<Double-Button-3>', mSwitch)
tout = tk.StringVar()

fontStyle = tkFont.Font(family='Consolas', size=80)
label = tk.Label(root, textvariable=tout, font=fontStyle, bg='black')
label.pack(expand='True', fill="both")

os.remove(tempFile)
root.geometry("260x200+200+200")
root.wm_attributes("-topmost", 1)
root.mainloop()
